### ISSUE TITLE
realpath bypassing `cd` calls yet follows symlinks and handles directory descent properly

### ISSUE THREAD

**Issue by pagerc** [ko1nksm/readlinkf#2] opened 2020-06-16 02:44 UTC
```
realpath() {
    _IFS=$IFS
    IFS='/'
    set -- $@
    DIR=$1
    case "${DIR}" in '') FULLPATH='/';; *) unset FULLPATH;; esac
    while shift ; do
        case "${DIR}" in
            ''|'.') DIR=$1 ; continue;;
            '..')
                DIR=$1
                BASENAME="${FULLPATH%/}"
                BASENAME="${BASENAME##*/}"
                case "${FULLPATH:0:1}${BASENAME}" in
                    '/') continue ;;
                    ''|'...')
                        case "${FULLPATH:0:1}" in
                            ''|'.') FULLPATH="${FULLPATH}../" ; continue;;
                        esac;;
                esac
                STRIPPATH="/${FULLPATH%/}"
                STRIPPATH="${STRIPPATH%/*}"
                case "${#STRIPPATH}" in 0|1) FULLPATH="${STRIPPATH}" ; continue;; esac
                FULLPATH="${STRIPPATH#/}/"
                continue
                ;;
        esac

        TARGET="${FULLPATH}${DIR}"
        if [ ! -L "${TARGET}" ] ; then
            FULLPATH="${TARGET}/"

        else
            LINK=$(readlink "${TARGET}")
            case "${LINK:0:1}" in '/') FULLPATH='/';; esac
            set -- $LINK $@
        fi
        DIR=$1
    done
    IFS=$_IFS
    printf '%s\n' "${FULLPATH%/}"
}
```

**Comment by ko1nksm** [comment] 2020-06-16 11:39
What does this solve? An alternative `realpath` command implementation?

The <code>cd **-P**</code> command is used to resolve logical directory to physical directory, not only to change directories. It can not be bypass for compatibility.

The `realpath` command may be useful in some situations, but I don't feel the need.

**Comment by pagerc** [comment] 2020-06-16 12:22
If the target path does not exist, this will dereference all symlinks and canonicalize the path for `mkdir -p`

**Comment by ko1nksm** [comment] 2021-01-04 14:12
This is not an issue with the `readlinkf` implementation in this repository, so I close it.

**Closed as completed by ko1nksm** 2021-01-04 14:12 UTC
Labels: not an issue

**Comment by pagerc** [comment] 2021-01-04 16:09
> This is not an issue with the `readlinkf` implementation in this repository, so I close it.

If the destination path does not exist, readlinkf will output nothing. My variation will output the symlink target.
The discrepancy is the symlink target existing vs not existing and the expected behavior of readlink.
The GNU version of readlink will output the target if the path does not exist. Your variation does not provide this compatibility.

**Comment by ko1nksm** [comment] 2021-01-05 14:43
It seems to be working correctly for me. Can you please provide a reproducible test case?

![image](https://user-images.githubusercontent.com/2453619/103660987-9145ab80-4fb1-11eb-9153-14af9e313555.png)

**Comment by pagerc** [comment] 2021-01-05 15:51
I was using the following `ln -s foo/bar test` then `readlink test` expected output is `foo/bar` what I get is an empty string.

**Comment by ko1nksm** [comment] 2021-01-05 16:01
![image](https://user-images.githubusercontent.com/2453619/103668382-5e53e580-4fba-11eb-8504-8f9ebcf6253d.png)

The output of the `exit status` is due to my `.bashrc` setting.

**Comment by pagerc** [comment] 2021-01-05 16:53
> ![image](https://user-images.githubusercontent.com/2453619/103668382-5e53e580-4fba-11eb-8504-8f9ebcf6253d.png)
> 
> The output of the `exit status` is due to my `.bashrc` setting.

Yep, that's a discrepancy from the GNU readlink behavior. Of which my code addresses by doing path munging.

**Comment by ko1nksm** [comment] 2021-01-05 17:09
My `readlinkf` is made to be fully compatible with GNU readlink, and as evident from the above results, `readlink -f` and `readlinkf` (`./readlink_posix`) return exactly the same result. I'm not talking about your code.

![image](https://user-images.githubusercontent.com/2453619/103676768-d4f5e080-4fc4-11eb-8430-3b0ba67b0cf9.png)
